// packages/core/src/utils/Animated/Animated.component.tsx
import { HTMLAttributes, CSSProperties, FC, useRef, useEffect, useMemo } from 'react';
import { jsx } from '@emotion/react';
import PropTypes from 'prop-types';
import anime from 'animejs';
import {
  ENTERING,
  EXITING,
  useAnimator
} from '@arwes/animation';

interface AnimatedSettingsTransitionFunctionParams {
  targets: anime.AnimeAnimParams['targets']
  duration: number
  delay?: number
}

type AnimatedSettingsTransitionFunction = (params: AnimatedSettingsTransitionFunctionParams) => void;

// TODO: Use a stronger typing for anime parameters instead of "anime.AnimeParams".
type AnimatedSettingsTransitionTypes = AnimatedSettingsTransitionFunction | anime.AnimeParams;

type AnimatedSettingsTransition = AnimatedSettingsTransitionTypes | AnimatedSettingsTransitionTypes[];

interface AnimatedSettings {
  initialStyle?: CSSProperties
  entering?: AnimatedSettingsTransition
  exiting?: AnimatedSettingsTransition
}

// TODO: Set proper HTML element typings according to "as" prop value.
// For now, all animated elements are asumed to be DIV elements.
interface AnimatedProps extends HTMLAttributes<HTMLDivElement> {
  as?: keyof HTMLElementTagNameMap
  animated?: AnimatedSettings
  className?: string
  style?: CSSProperties
}

const Animated: FC<AnimatedProps> = props => {
  const {
    as: asProvided,
    animated,
    className,
    style,
    children,
    ...otherProps
  } = props;

  const as = useMemo(() => asProvided || 'div', []);

  // TODO: Add external root ref.
  const rootRef = useRef<HTMLDivElement>();

  const animator = useAnimator();

  const dynamicStyle = animator?.animate
    ? animated?.initialStyle
    : null;

  useEffect(() => {
    return () => {
      anime.remove(rootRef.current as HTMLDivElement);
    };
  }, []);

  useEffect(() => {
    if (!animator || !animator.animate || !animated) {
      return;
    }

    switch (animator.flow.value) {
      case ENTERING: {
        if (animated.entering) {
          const animationParams = {
            targets: rootRef.current,
            duration: animator.duration.enter
          };

          const animations: AnimatedSettingsTransitionTypes[] =
            Array.isArray(animated.entering)
              ? animated.entering
              : [animated.entering];

          animations.forEach(animation => {
            if (typeof animation === 'function') {
              animation(animationParams);
            }
            else {
              anime({
                easing: 'easeOutSine',
                ...animation,
                targets: rootRef.current,
                duration: animator.duration.enter
              });
            }
          });
        }
        break;
      }

      case EXITING: {
        if (animated.exiting) {
          const animationParams = {
            targets: rootRef.current,
            duration: animator.duration.exit
          };

          const animations: AnimatedSettingsTransitionTypes[] =
            Array.isArray(animated.exiting)
              ? animated.exiting
              : [animated.exiting];

          animations.forEach(animation => {
            if (typeof animation === 'function') {
              animation(animationParams);
            }
            else {
              anime({
                easing: 'easeOutSine',
                ...animation,
                targets: rootRef.current,
                duration: animator.duration.exit
              });
            }
          });
        }
        break;
      }
    }
  }, [animator?.flow]);

  return jsx(as, {
    ...otherProps,
    className,
    style: {
      ...style,
      ...dynamicStyle
    },
    ref: rootRef
  }, children);
};

Animated.propTypes = {
  // @ts-expect-error
  as: PropTypes.string.isRequired,
  // @ts-expect-error
  animated: PropTypes.shape({
    initialStyle: PropTypes.object,
    entering: PropTypes.oneOfType([
      PropTypes.func,
      PropTypes.object,
      PropTypes.arrayOf(
        PropTypes.oneOfType([
          PropTypes.func,
          PropTypes.object
        ])
      )
    ]),
    exiting: PropTypes.oneOfType([
      PropTypes.func,
      PropTypes.object,
      PropTypes.arrayOf(
        PropTypes.oneOfType([
          PropTypes.func,
          PropTypes.object
        ])
      )
    ])
  })
};

Animated.defaultProps = {
  as: 'div'
};

export {
  AnimatedSettingsTransitionFunctionParams,
  AnimatedSettingsTransitionFunction,
  AnimatedSettingsTransition,
  AnimatedProps,
  Animated
};

// packages/animated/src/Animated/Animated.component.ts
import {
  HTMLProps,
  SVGProps,
  CSSProperties,
  MutableRefObject,
  ReactNode,
  ReactElement,
  createElement,
  useRef,
  useEffect,
  useMemo,
  useCallback
} from 'react';
import PropTypes from 'prop-types';
import anime from 'animejs';
import { ENTERING, EXITING, useAnimator } from '@arwes/animator';

import { AnimatedSettings } from '../constants';
import { NoInfer } from '../utils/types';
import { formatAnimatedCSSPropsShorthands } from './formatAnimatedCSSPropsShorthands';

interface AnimatedProps <E extends HTMLElement | SVGElement = HTMLElement, P = HTMLProps<HTMLElement>> {
  as?: keyof HTMLElementTagNameMap | keyof SVGElementTagNameMap
  animated?: AnimatedSettings<P> | Array<AnimatedSettings<P>>
  className?: string
  style?: CSSProperties
  rootRef?: MutableRefObject<E | null> | ((node: E) => void)
  children?: ReactNode
}

const Animated = <
  E extends HTMLElement | SVGElement = HTMLDivElement,
  P extends HTMLProps<HTMLElement> | SVGProps<SVGElement> = HTMLProps<HTMLDivElement>
> (props: AnimatedProps<E, P> & NoInfer<P>): ReactElement => {
  const {
    as: asProvided,
    animated,
    className,
    style,
    rootRef: externalRef,
    ...otherProps
  } = props;

  const as = useMemo(() => asProvided || 'div', []);

  const internalRef = useRef<E | null>(null);

  const rootRef = useCallback((node: E) => {
    internalRef.current = node;

    if (typeof externalRef === 'function') {
      externalRef(node);
    }
    else if (externalRef) {
      externalRef.current = node;
    }
  }, []);

  const animator = useAnimator();

  if (process.env.NODE_ENV !== 'production' && !animator) {
    throw new Error('Animated component can only be used inside an Animator.');
  }

  const { animate } = animator || {};

  const animatedItemsReceived = Array.isArray(animated) ? animated : [animated];
  const animatedItems = animatedItemsReceived.filter(Boolean) as Array<AnimatedSettings<P>>;

  useEffect(() => {
    return () => {
      anime.remove(internalRef.current);
    };
  }, []);

  useEffect(() => {
    if (!animator || !animator.animate || !animated) {
      return;
    }

    switch (animator.flow.value) {
      case ENTERING: {
        const animationParams = {
          targets: internalRef.current,
          duration: animator.duration.enter
        };

        animatedItems.filter(item => item.entering).forEach(item => {
          const animations = Array.isArray(item.entering) ? item.entering : [item.entering];

          animations.forEach(animation => {
            if (typeof animation === 'function') {
              animation(animationParams);
            }
            else {
              anime({
                easing: 'easeOutSine',
                ...animation,
                targets: internalRef.current,
                duration: animator.duration.enter
              });
            }
          });
        });

        break;
      }

      case EXITING: {
        const animationParams = {
          targets: internalRef.current,
          duration: animator.duration.exit
        };

        animatedItems.filter(item => item.exiting).forEach(item => {
          const animations = Array.isArray(item.exiting) ? item.exiting : [item.exiting];

          animations.forEach(animation => {
            if (typeof animation === 'function') {
              animation(animationParams);
            }
            else {
              anime({
                easing: 'easeOutSine',
                ...animation,
                targets: internalRef.current,
                duration: animator.duration.exit
              });
            }
          });
        });

        break;
      }
    }
  }, [animator?.flow]);

  let initialAttributes: P | undefined;
  if (animate) {
    initialAttributes = animatedItems
      .map(item => item?.initialAttributes)
      .reduce((total: any, item) => ({ ...total, ...item }), {});
  }

  let dynamicStyles: CSSProperties | undefined;
  if (animate) {
    dynamicStyles = animatedItems
      .map(item => formatAnimatedCSSPropsShorthands(item?.initialStyles))
      .reduce((total, item) => ({ ...total, ...item }), {});
  }

  return createElement(as, {
    ...otherProps,
    ...initialAttributes,
    className,
    style: {
      ...style,
      ...dynamicStyles
    },
    ref: rootRef
  });
};

const animatedSettingsPropType = PropTypes.shape({
  initialAttributes: PropTypes.object,
  initialStyles: PropTypes.object,
  entering: PropTypes.oneOfType([
    PropTypes.func,
    PropTypes.object,
    PropTypes.arrayOf(
      PropTypes.oneOfType([
        PropTypes.func,
        PropTypes.object
      ])
    )
  ]),
  exiting: PropTypes.oneOfType([
    PropTypes.func,
    PropTypes.object,
    PropTypes.arrayOf(
      PropTypes.oneOfType([
        PropTypes.func,
        PropTypes.object
      ])
    )
  ])
});

Animated.propTypes = {
  as: PropTypes.string.isRequired,
  animated: PropTypes.oneOfType([
    animatedSettingsPropType,
    PropTypes.arrayOf(animatedSettingsPropType)
  ])
};

Animated.defaultProps = {
  as: 'div'
};

export { AnimatedProps, Animated };
